on:
  rss:
    url: https://www.instapaper.com/rss/7852146/1XdK2Pf66PNeq9bbBhksjh5FFLk
jobs:
  add:
    name: Add new task
    runs-on: ubuntu-latest
    steps:
      - uses: ahonn/add-dida365-task-action@v0.2.0
        with:
          emailOrPhone: ${{ secrets.DIDA365_EMAIL }}
          password: ${{ secrets.DIDA365_PASSWORD }}
          task: '${{ on.rss.outputs.title }} ${{ on.rss.outputs.link }}'

